name: olist-ecommerce

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-dw
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Olist_dw
    ports:
      - "5433:5432"
    volumes:
      - olist_data:/var/lib/postgresql/data

volumes:
  olist_data: